[package]
name = "reing_text2image"
version = "0.1.0"
authors = ["Yusuke Sangenya <longinus.eva@gmail.com>"]

[lib]
name = "reing_text2image"
path = "src/lib.rs"

[[bin]]
name = "text2image"
path = "src/main.rs"

[dependencies]
image = "0.19.0"
imageproc = "0.15.0"
rusttype = "0.5.2"

clap = "*"
